M48
; DRILL file KiCad 10.0.6 date 2026-09-10T23:49:14
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-10T23:49:14+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.100
%
G90
G05
T1
X189.445Y-98.505
X189.445Y-103.505
T2
X158.17Y-97.85
X158.17Y-100.85
T3
X159.0Y-91.5
X159.0Y-119.0
X191.0Y-91.5
X191.0Y-119.0
M30
